project:
  type: website
  output-dir: docs
  
website:
  title: "Sadraque Lucena"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: instagram
        href: https://www.instagram.com/saeflu/
      - icon: github
        href: https://github.com/sadraquelucena/website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Sadraque Lucena"

format:
  html:
    theme: cerulean
    toc: true

editor: source

